#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

_clear
printf '\n%s%s  Klarspråk · credential/provider prerequisite wizard%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  Inga token- eller secretvärden samlas in, skrivs eller visas.%s\n\n' "$DIM" "$RESET"
pause "Ready to verify Klarspråk provider state?"

stage "Worker runtime · admin + Turnstile"
say "Verifiera de credentialnamn som faktiskt skyddar admin- och submissionflödena."
open_url "https://dash.cloudflare.com/"
step "Öppna Workers & Pages → klarsprak → Settings och verifiera ADMIN_TOKEN och TURNSTILE_SECRET utan att visa eller kopiera värden."
step "RATE_LIMIT_KEY är valfri. Om den saknas använder runtime ADMIN_TOKEN som HMAC-nyckel för rate-limit-identitet; dokumentera detta som avsiktlig fallback i stället för att skapa en ny secret bara för wizarden."
step "Verifiera att TURNSTILE_HOSTNAMES tillåter canonical host klarsprak.denied.se. IDN-aliaset ska redirecta till canonical host innan submission och behöver därför inte vara en separat Turnstile-host."
if ! confirm "Är admin-/Turnstile-konfigurationen närvarande och är eventuell RATE_LIMIT_KEY-state avsiktlig?"; then
  warn "Runtime credential-state är inte ens konfigurationsmässigt verifierad."
  exit 2
fi

stage "ADMIN_TOKEN · end-to-end"
say "Verifiera admincredentialen genom den befintliga read-only adminytan."
open_url "https://klarsprak.denied.se/admin"
step "Hämta ADMIN_TOKEN från dess säkra operatörskälla och skriv den endast i sidans lösenordsfält. Klistra aldrig in tokenen i denna wizard, Git, PR eller logg."
step "Tryck 'Ladda' och verifiera att Granskningskö/Publicerade termer kan läsas utan 401. Tokenen ska endast ligga i sessionStorage för den aktuella fliken."
step "Utför ingen approve/reject/update/status-mutation som credentialtest."
if ! confirm "Ger aktuell ADMIN_TOKEN autentiserad read-only adminåtkomst?"; then
  warn "ADMIN_TOKEN är inte end-to-end-verifierad."
  exit 2
fi

stage "Turnstile · legitim submission-evidens"
say "Verifiera Turnstile utan att skapa syntetiskt publiceringsinnehåll."
open_url "https://dash.cloudflare.com/"
step "Öppna Turnstile och verifiera den widget/site-key som används av Klarspråks submission samt att secretet motsvarar Worker-runtime."
step "Kräv evidens från en legitim submission efter senaste Turnstile-secret-rotation: siteverify ska ha accepterat action term_submit och submission ska ha hamnat i pending review-state."
step "Om ingen legitim post-rotation submission finns: markera TURNSTILE_SECRET som konfigurerad men funktionellt overifierad och stoppa här. Skapa inte en falsk term enbart för testet."
step "Publik GET /api/terms är inte credentialbevis för Turnstile."
if ! confirm "Finns legitim post-rotation Turnstile-evidens för term_submit?"; then
  warn "TURNSTILE_SECRET är inte funktionellt verifierad."
  exit 2
fi

stage "D1 + production ingress"
say "Verifiera state/liveness separat från credentialbevis."
open_url "https://dash.cloudflare.com/"
step "Verifiera D1-binding DB → klarsprak-db-eu och att databasen fortsatt är EU-jurisdiction enligt repositoryts driftkontrakt."
open_url "https://klarsprak.denied.se/"
step "Verifiera canonical root HTTP 200, GET /api/terms HTTP 200 med JSON terms-array och IDN-aliasets 301 till canonical root, motsvarande npm run verify:production."
step "Dessa publika kontroller bevisar routing/D1-liveness men ersätter inte ADMIN_TOKEN- eller Turnstile-verifieringen ovan."
if ! confirm "Är D1-binding och productioningress gröna?"; then
  warn "Runtime/liveness är overifierad."
  exit 2
fi

stage "Cloudflare Workers Builds"
say "Verifiera provider-managed buildkontrakt utan att uppfinna ett repo-script som inte finns."
open_url "https://dash.cloudflare.com/"
step "Öppna Workers & Pages → klarsprak → Builds/Settings och verifiera repository Avkroken/Klarsprak samt production branch main."
step "Verifiera den faktiskt konfigurerade production build/deploy command i Cloudflare mot current provider-state. Repositoryt deklarerar i dag inte ett deploy:workers-builds-script, så wizarden får inte anta ett sådant kommando."
step "Kräv en aktuell lyckad GitHub-check 'Workers Builds: klarsprak' efter senaste relevanta secret-/bindingändring."
step "GitHub Actions ska inte få en ny Cloudflare deploycredential för att duplicera Workers Builds."
if ! confirm "Är current Workers Builds-konfiguration verifierad live och senaste main-check grön?"; then
  warn "Deployidentiteten är overifierad tills provider-state och aktuell build är gröna."
  exit 2
fi

finish
