name: Central metadata routing

on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
  schedule:
    - cron: '39 * * * *'
  workflow_dispatch:

permissions: {}

jobs:
  metadata:
    permissions:
      issues: write
      pull-requests: write
    uses: Avkroken/.github/.github/workflows/metadata-orchestration.yml@2baaff1ee7c0193908076328c530b5f2ef9acda6
